spring:
  application:
    name: rate-limiter-service

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  endpoint:
    health:
      show-details: always


rate-limiting:
  plans:
    free:
      capacity: 10
      refill-rate: 10
      refill-period: 1
      time-unit: MINUTES
    premium:
      capacity: 100
      refill-rate: 100
      refill-period: 1
      time-unit: SECONDS